#!/usr/bin/python

import sys, getopt, subprocess

def spawn(mode, publisher, subscriber, output):
  for s in range(0, subscriber):
    subprocess.Popen(
      'node app.js -m %s -n %d -s subscriber%d -o %s &' \
        % (mode, publisher, s + 1, output),
      shell=True
    )
  for p in range(0, publisher):
    subprocess.Popen(
      'node app.js -m %s -n %d -p publisher%d -o %s &' \
        % (mode, publisher, p + 1, output),
      shell=True
    )

def help():
  return \
      'Usage: \n\
      -m --mode\n\
      -p --publisher\n\
      -s --subscriber\n\
      -o --output'

def main(argv):
  try:
    opts, args = getopt.getopt(
      argv,
      'hm:p:s:o:', [
        'mode=',
        'publisher=',
        'subscriber=',
        'ouput='
      ]
    )
  except getopt.GetoptError, e:
    print e
    sys.exit(2)

  mode, publisher, subscriber, output = '', '', '', ''
  for opt, arg in opts:
    if opt == '-h':
      print help()
      sys.exit()
    elif opt in ('-m', '--mode'):
      mode = arg
    elif opt in ('-p', '--publisher'):
      publisher = int(arg)
    elif opt in ('-s', '--subscriber'):
      subscriber = int(arg)
    elif opt in ('-o', '--output'):
      output = arg

  if '' not in (mode, publisher, subscriber, output):
    spawn(mode, publisher, subscriber, output)
  else:
    print help()

if __name__ == '__main__':
  main(sys.argv[1:])
